// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWIZpjYRjePGuyi0n-OVG7XkRfj_77evc',
    appId: '1:187359709525:web:94c6eb38cfc4a0e04387dc',
    messagingSenderId: '187359709525',
    projectId: 'biznet-byct',
    authDomain: 'biznet-byct.firebaseapp.com',
    storageBucket: 'biznet-byct.firebasestorage.app',
    measurementId: 'G-KCT2X43R7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAInerZkrH1_iSw6WWiJuqbVwpL6I9M1g8',
    appId: '1:187359709525:android:b385dbe87d063f074387dc',
    messagingSenderId: '187359709525',
    projectId: 'biznet-byct',
    storageBucket: 'biznet-byct.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA_71ppBnYecOjGqPy0vBwbSDJLlOYhZs',
    appId: '1:187359709525:ios:092cdf0416d853cb4387dc',
    messagingSenderId: '187359709525',
    projectId: 'biznet-byct',
    storageBucket: 'biznet-byct.firebasestorage.app',
    iosBundleId: 'com.example.biznet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA_71ppBnYecOjGqPy0vBwbSDJLlOYhZs',
    appId: '1:187359709525:ios:092cdf0416d853cb4387dc',
    messagingSenderId: '187359709525',
    projectId: 'biznet-byct',
    storageBucket: 'biznet-byct.firebasestorage.app',
    iosBundleId: 'com.example.biznet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWIZpjYRjePGuyi0n-OVG7XkRfj_77evc',
    appId: '1:187359709525:web:f6e222adb07ad1d54387dc',
    messagingSenderId: '187359709525',
    projectId: 'biznet-byct',
    authDomain: 'biznet-byct.firebaseapp.com',
    storageBucket: 'biznet-byct.firebasestorage.app',
    measurementId: 'G-PSD2R6LH3S',
  );
}
